version: 0.1.0-{build}

environment:
  AZURE_KEY:
    secure: Px0wZ+FveTB9pYNhfwVyqeeK8mUC0PgOe55p9WX2oQ+yMlUyb3hp/YOmfBuOtxo+

cache: 
  - .\dotnet\packages
  - .\node_modules

before_build:
  - cmd: npm install
  - cmd: dotnet restore .\dotnet --configfile .\dotnet\nuget.config --packages .\dotnet\packages --verbosity Minimal



artifacts:
  - path: .\dotnet\artifacts

test: off


after_deploy:
  - cmd: .\node_modules\.bin\wdio

branches:
  only:
    - develop
    - master

clone_depth: 5
