version: 0.1.{build}

environment:
  AZURE_KEY:
    secure: Px0wZ+FveTB9pYNhfwVyqeeK8mUC0PgOe55p9WX2oQ+yMlUyb3hp/YOmfBuOtxo+

build:
  project: dotnet\TheEight.sln
  verbosity: minimal

branches:
  only:
  - develop
  - master

before_build:
- cmd: dotnet restore dotnet
