version: 0.1.0-{build}

environment:
  AZURE_KEY:
    secure: Px0wZ+FveTB9pYNhfwVyqeeK8mUC0PgOe55p9WX2oQ+yMlUyb3hp/YOmfBuOtxo+

before_build:
- cmd: dotnet restore .\dotnet --configfile .\dotnet\nuget.config --verbosity Error

build_script:
- cmd: dotnet build .\dotnet\src\TheEight.WebApp

after_build:
- cmd: dotnet publish .\dotnet\src\TheEight.WebApp --version-suffix %APPVEYOR_BUILD_NUMBER%

artifacts:
- path: .\dotnet\artifacts
  name: WebDeploy
  type: WebDeployPackage

deploy:
- provider: WebDeploy
  server: https://the8-dev.scm.azurewebsites.net:443/msdeploy.axd?site=the8-dev
  website: the8-dev
  username: $the8-dev
  password:
    secure: IowojYjSU3gwHS58Ej4VhbvEGldNwvRCb/IvktrZU+ATY5hewAMwQ179Fy4wnp7Tbi6Vnm8KhoMSKleYbOtoyg==
  aspnet_core: true

branches:
  only:
  - develop
  - master
