version: 0.1.0-{build}

environment:
  AZURE_KEY:
    secure: Px0wZ+FveTB9pYNhfwVyqeeK8mUC0PgOe55p9WX2oQ+yMlUyb3hp/YOmfBuOtxo+

build: off

artifacts:
  - path: .\dotnet\artifacts

test: off


on_finish:
  - cmd: .\node_modules\.bin\wdio

branches:
  only:
    - develop
    - master

clone_depth: 5
