version: 0.1.0-{build}

environment:
  AZURE_KEY:
    secure: Px0wZ+FveTB9pYNhfwVyqeeK8mUC0PgOe55p9WX2oQ+yMlUyb3hp/YOmfBuOtxo+

cache: 
  - .\dotnet\packages
  - .\node_modules

install:
  - cmd: npm install
  - cmd: npm link gulp

before_build:
  - cmd: dotnet restore .\dotnet --configfile .\dotnet\nuget.config --packages .\dotnet\packages --verbosity Minimal

build_script:
  - cmd: gulp build:ci --cwd .\ui\tools
  - cmd: cd .\dotnet\src\TheEight.WebApp
  - cmd: dotnet build
  - cmd: dotnet publish --output ..\..\artifacts --version-suffix %APPVEYOR_BUILD_NUMBER%
  - cmd: cd ..\..\..

artifacts:
  - path: .\dotnet\artifacts

test: off

deploy:
  - provider: WebDeploy
    server: https://the8-dev.scm.azurewebsites.net:443/msdeploy.axd?site=the8-dev
    remove_files: false
    app_offline: true
    website: the8-dev
    username: $the8-dev
    password:
      secure: IowojYjSU3gwHS58Ej4VhbvEGldNwvRCb/IvktrZU+ATY5hewAMwQ179Fy4wnp7Tbi6Vnm8KhoMSKleYbOtoyg==
    aspnet_core: true

after_deploy:
  - cmd: gulp e2e-test:ci --cwd .\e2e-tests

branches:
  only:
    - develop
    - master

clone_depth: 5
