CREATE VIEW [dbo].[__ENSURE_EVENT_NOT_BOTH_WATER_AND_ERG]
WITH SCHEMABINDING AS 
	SELECT 
		evt.[EventId]
	FROM [dbo].[EVENTS] AS evt
	CROSS JOIN [dbo].[WATER_EVENTS] AS wat
	CROSS JOIN [dbo].[ERG_EVENTS] AS erg
	WHERE wat.[EventId] = evt.[EventId]
		OR erg.[EventId] = evt.[EventId]
		
GO

CREATE UNIQUE CLUSTERED INDEX [IX__ENSURE_EVENT_NOT_BOTH_WATER_AND_ERG] 
	ON [dbo].[__ENSURE_EVENT_NOT_BOTH_WATER_AND_ERG] ([EventId])
