CREATE VIEW [dbo].[__ENSURE_EVENT_ATTENDEE_NOT_BOTH_TEAM_MEMBER_AND_GUEST]
WITH SCHEMABINDING AS 
	SELECT 
		attn.[AttendeeId]
	FROM [dbo].[EVENT_ATTENDEES] AS attn
	CROSS JOIN [dbo].[TEAM_MEMBER_EVENT_ATTENDEES] AS tm
	CROSS JOIN [dbo].[GUEST_EVENT_ATTENDEES] AS gst
	WHERE tm.[AttendeeId] = attn.[AttendeeId]
		OR gst.[AttendeeId] = attn.[AttendeeId]
		
GO

CREATE UNIQUE CLUSTERED INDEX [IX__ENSURE_EVENT_ATTENDEE_NOT_BOTH_TEAM_MEMBER_AND_GUEST] 
	ON [dbo].[__ENSURE_EVENT_ATTENDEE_NOT_BOTH_TEAM_MEMBER_AND_GUEST] ([AttendeeId])