CREATE TABLE [dbo].[ATTENDEES]
(
	[AttendeeId] UNIQUEIDENTIFIER NOT NULL, 
    [EventId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK__ATTENDEES] PRIMARY KEY ([AttendeeId]), 
    CONSTRAINT [FK__ATTENDEES__EVENTS] FOREIGN KEY ([EventId]) REFERENCES [EVENTS]([EventId])
)
