CREATE TABLE [dbo].[CLUBS]
(
	[ClubId] UNIQUEIDENTIFIER NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK__CLUBS] PRIMARY KEY ([ClubId]), 
    CONSTRAINT [AK__CLUBS__Name] UNIQUE ([Name])
)
