CREATE TABLE [dbo].[CLUB_ROLES]
(
	[RoleId] TINYINT NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK__CLUB_ROLES] PRIMARY KEY ([RoleId]), 
    CONSTRAINT [AK__CLUB_ROLES__Name] UNIQUE ([Name]) 
)
