CREATE TABLE [dbo].[CLUB_MEMBERS]
(
    [ClubMemberId] UNIQUEIDENTIFIER NOT NULL, 
    [UserId] UNIQUEIDENTIFIER NOT NULL, 
    [ClubId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK__CLUB_MEMBERS] PRIMARY KEY ([ClubMemberId]), 
    CONSTRAINT [FK__CLUB_MEMBERS__USERS] FOREIGN KEY ([UserId]) REFERENCES [USERS]([UserId]),
    CONSTRAINT [FK__CLUB_MEMBERS__CLUBS] FOREIGN KEY ([ClubId]) REFERENCES [CLUBS]([ClubId]), 
    CONSTRAINT [AK__CLUB_MEMBERS__UserId__ClubId] UNIQUE ([UserId], [ClubId])
)
