CREATE TABLE [dbo].[ERG_EVENT_PIECE_TYPES]
(
	[PieceTypeId] TINYINT NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK__ERG_EVENT_PIECE_TYPES] PRIMARY KEY ([PieceTypeId]), 
    CONSTRAINT [AK__ERG_EVENT_PIECE_TYPES__Name] UNIQUE ([Name]) 
)
