CREATE TABLE [dbo].[GLOBAL_ROLES]
(
	[GlobalRoleId] TINYINT NOT NULL, 
    [Name] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK__GLOBAL_ROLES] PRIMARY KEY ([GlobalRoleId]), 
    CONSTRAINT [AK__GLOBAL_ROLES__Name] UNIQUE ([Name])
)
