CREATE TABLE [dbo].[GUEST_EVENT_ATTENDEES]
(
	[AttendeeId] UNIQUEIDENTIFIER NOT NULL, 
    [GivenName] NVARCHAR(50) NOT NULL, 
    [Surname] NVARCHAR(50) NULL, 
    CONSTRAINT [PK__GUEST_EVENT_ATTENDEES] PRIMARY KEY ([AttendeeId]) 
)
