CREATE TABLE [dbo].[INVITEES_IN_GLOBAL_ROLES]
(
	[InviteId] UNIQUEIDENTIFIER NOT NULL , 
    [GlobalRoleId] TINYINT NOT NULL, 
    CONSTRAINT [PK__INVITEES_IN_GLOBAL_ROLES] PRIMARY KEY ([InviteId]), 
    CONSTRAINT [FK__INVITEES_IN_GLOBAL_ROLES__GLOBAL_ROLES] FOREIGN KEY ([GlobalRoleId]) 
        REFERENCES [GLOBAL_ROLES]([RoleId]), 
    CONSTRAINT [FK__INVITEES_IN_GLOBAL_ROLES__INVITES] FOREIGN KEY ([InviteId]) 
        REFERENCES [INVITES]([InviteId]) 
)
