CREATE TABLE [dbo].[INVITEES_IN_CLUB_ROLES]
(
	[InviteId] UNIQUEIDENTIFIER NOT NULL, 
    [ClubId] UNIQUEIDENTIFIER NOT NULL, 
    [ClubRoleId] TINYINT NOT NULL, 
    CONSTRAINT [PK__INVITEES_IN_CLUB_ROLES] PRIMARY KEY ([ClubRoleId], [InviteId], [ClubId]), 
    CONSTRAINT [FK__INVITEES_IN_CLUB_ROLES__INVITES] FOREIGN KEY ([InviteId]) 
        REFERENCES [INVITES]([InviteId]), 
    CONSTRAINT [FK__INVITEES_IN_CLUB_ROLES__CLUBS] FOREIGN KEY ([ClubId]) 
        REFERENCES [CLUBS]([ClubId]), 
    CONSTRAINT [FK__INVITEES_IN_CLUB_ROLES__CLUB_ROLES] FOREIGN KEY ([ClubRoleId]) 
        REFERENCES [CLUB_ROLES]([RoleId]) 
)
