CREATE TABLE [dbo].[TEAM_MEMBERS]
(
	[ClubMemberUserId] UNIQUEIDENTIFIER NOT NULL, 
    [TeamId] UNIQUEIDENTIFIER NOT NULL, 
    [PreferredBoatPositionId] TINYINT NOT NULL, 
    CONSTRAINT [PK__TEAM_MEMBERS] PRIMARY KEY ([TeamId], [ClubMemberUserId]), 
    CONSTRAINT [FK__TEAM_MEMBERS__CLUB_MEMBERS] FOREIGN KEY ([ClubMemberUserId]) 
		REFERENCES [CLUB_MEMBERS]([UserId]), 
	CONSTRAINT [FK__TEAM_MEMBERS__TEAMS] FOREIGN KEY ([TeamId]) REFERENCES [TEAMS]([TeamId]), 
    CONSTRAINT [FK__TEAM_MEMBERS__BOAT_POSITIONS] FOREIGN KEY ([PreferredBoatPositionId]) 
		REFERENCES [BOAT_POSITIONS]([BoatPositionId])
)
