CREATE TABLE [dbo].[TEAM_MEMBERS]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL, 
    [TeamId] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK__TEAM_MEMBERS] PRIMARY KEY ([TeamId], [UserId]), 
    CONSTRAINT [FK__TEAM_MEMBERS__CLUB_MEMBERS] FOREIGN KEY ([UserId]) REFERENCES [CLUB_MEMBERS]([UserId]), 
	CONSTRAINT [FK__TEAM_MEMBERS__TEAMS] FOREIGN KEY ([TeamId]) REFERENCES [TEAMS]([TeamId])
)
