CREATE TABLE [dbo].[TEAM_MEMBERS]
(
	[TeamMemberId] UNIQUEIDENTIFIER NOT NULL,
	[ClubMemberId] UNIQUEIDENTIFIER NOT NULL, 
    [TeamId] UNIQUEIDENTIFIER NOT NULL, 
    [PreferredBoatPositionId] TINYINT NOT NULL, 
    CONSTRAINT [PK__TEAM_MEMBERS] PRIMARY KEY ([TeamMemberId]), 
    CONSTRAINT [FK__TEAM_MEMBERS__CLUB_MEMBERS] FOREIGN KEY ([ClubMemberId]) 
		REFERENCES [CLUB_MEMBERS]([ClubMemberId]), 
	CONSTRAINT [FK__TEAM_MEMBERS__TEAMS] FOREIGN KEY ([TeamId]) REFERENCES [TEAMS]([TeamId]), 
    CONSTRAINT [FK__TEAM_MEMBERS__BOAT_POSITIONS] FOREIGN KEY ([PreferredBoatPositionId]) 
		REFERENCES [BOAT_POSITIONS]([BoatPositionId]), 
    CONSTRAINT [AK__TEAM_MEMBERS__ClubMemberId__TeamId] UNIQUE ([ClubMemberId], [TeamId])
)
