CREATE TABLE [dbo].[TEAM_MEMBERS_IN_TEAM_ROLES]
(
	[TeamMemberId] UNIQUEIDENTIFIER NOT NULL, 
    [TeamRoleId] TINYINT NOT NULL, 
    CONSTRAINT [PK__TEAM_MEMBERS_IN_TEAM_ROLES] PRIMARY KEY ([TeamMemberId], [TeamRoleId]), 
    CONSTRAINT [FK__TEAM_MEMBERS_IN_TEAM_ROLES__TEAM_MEMBERS] FOREIGN KEY ([TeamMemberId]) 
		REFERENCES [TEAM_MEMBERS]([TeamMemberId]),
    CONSTRAINT [FK__TEAM_MEMBERS_IN_TEAM_ROLES__TEAM_ROLES] FOREIGN KEY ([TeamRoleId]) 
		REFERENCES [TEAM_ROLES]([TeamRoleId])
)
