CREATE TABLE [dbo].[TEAM_MEMBERS_IN_TEAM_ROLES]
(
	[TeamMemberUserId] UNIQUEIDENTIFIER NOT NULL , 
    [TeamRoleId] TINYINT NOT NULL, 
    CONSTRAINT [PK__TEAM_MEMBERS_IN_TEAM_ROLES] PRIMARY KEY ([TeamMemberUserId], [TeamRoleId])
)
