CREATE TABLE [dbo].[USERS_IN_GLOBAL_ROLES]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL,
	[GlobalRoleId] TINYINT NOT NULL, 
    CONSTRAINT [PK__USERS_IN_GLOBAL_ROLES] PRIMARY KEY ([UserId], [GlobalRoleId]), 
    CONSTRAINT [FK__USERS_IN_GLOBAL_ROLES__USERS] FOREIGN KEY ([UserId]) REFERENCES [USERS]([UserId]), 
    CONSTRAINT [FK__USERS_IN_GLOBAL_ROLES__GLOBAL_ROLES] FOREIGN KEY ([GlobalRoleId]) REFERENCES [GLOBAL_ROLES]([GlobalRoleId])
)
