CREATE TABLE [dbo].[WATER_EVENT_ATTENDEES]
(
	[WaterEventAttendeeId] UNIQUEIDENTIFIER NOT NULL, 
    [WaterEventId] UNIQUEIDENTIFIER NOT NULL, 
    [GivenName] NVARCHAR(50) NOT NULL, 
    [Surname] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK_WATER_EVENT_ATTENDEES] PRIMARY KEY ([WaterEventAttendeeId])
)
