CREATE TABLE [dbo].[WATER_EVENT_BOATS]
(
	[WaterEventBoatId] UNIQUEIDENTIFIER NOT NULL, 
	[WaterEventId] UNIQUEIDENTIFIER NOT NULL,
    [Title] NVARCHAR(50) NOT NULL, 
    [SeatCount] TINYINT NOT NULL, 
    [IsCoxed] BIT NOT NULL, 
    CONSTRAINT [PK__WATER_EVENT_BOATS] PRIMARY KEY ([WaterEventBoatId]), 
    CONSTRAINT [FK__WATER_EVENT_BOATS__WATER_EVENTS] FOREIGN KEY ([WaterEventId]) REFERENCES [WATER_EVENTS]([EventId])
)
