CREATE TABLE [dbo].[WATER_EVENT_PLACEMENTS]
(
    [AttendeeId] UNIQUEIDENTIFIER NOT NULL, 
    [BoatId] UNIQUEIDENTIFIER NOT NULL, 
    [SeatNumber] TINYINT NOT NULL, 
    CONSTRAINT [PK__WATER_EVENT_PLACEMENTS] PRIMARY KEY ([AttendeeId], [BoatId]), 
    CONSTRAINT [AK__WATER_EVENT_PLACEMENTS__SeatNumber__BoatId] UNIQUE ([SeatNumber], [BoatId]) 
)
