CREATE TABLE [dbo].[BOAT_POSITIONS]
(
	[BoatPositionId] TINYINT NOT NULL , 
    [Name] NVARCHAR(50) NOT NULL, 
    CONSTRAINT [PK__BOAT_POSITIONS] PRIMARY KEY ([BoatPositionId]), 
    CONSTRAINT [AK__BOAT_POSITIONS__Name] UNIQUE ([Name])
)
