CREATE TABLE [dbo].[INVITEES_IN_TEAM_ROLES]
(
	[InviteId] UNIQUEIDENTIFIER NOT NULL, 
    [TeamId] UNIQUEIDENTIFIER NOT NULL, 
    [TeamRoleId] TINYINT NOT NULL, 
    CONSTRAINT [PK__INVITEES_IN_TEAM_ROLES] PRIMARY KEY ([InviteId], [TeamRoleId], [TeamId]), 
    CONSTRAINT [FK__INVITEES_IN_TEAM_ROLES__TEAM_ROLES] FOREIGN KEY ([TeamRoleId]) 
        REFERENCES [TEAM_ROLES]([TeamRoleId]), 
    CONSTRAINT [FK__INVITEES_IN_TEAM_ROLES__TEAM_INVITES] FOREIGN KEY ([InviteId]) 
        REFERENCES [INVITES]([InviteId]) 
)
