CREATE TABLE [dbo].[WATER_EVENTS]
(
	[EventId] UNIQUEIDENTIFIER NOT NULL, 
    [WaterEventModeId] TINYINT NOT NULL, 
    CONSTRAINT [PK__WATER_EVENTS] PRIMARY KEY ([EventId]), 
	CONSTRAINT [FK__WATER_EVENTS__EVENTS] FOREIGN KEY ([EventId]) 
		REFERENCES [EVENTS]([EventId]),
    CONSTRAINT [FK__WATER_EVENTS__WATER_EVENT_MODES] FOREIGN KEY ([WaterEventModeId]) 
		REFERENCES [WATER_EVENT_MODES]([WaterEventModeId])
)
