export const ASSIGN_ATTENDEE = "ASSIGN_ATTENDEE";
export const UNASSIGN_ATTENDEE = "UNASSIGN_ATTENDEE";
export const CHANGE_EVENT_DETAILS = "CHANGE_EVENT_DETAILS";
export const CREATE_BOAT = "CREATE_BOAT";
export const CREATE_ATTENDEE = "CREATE_ATTENDEE";