const ASSIGN_ATTENDEE = "ASSIGN_ATTENDEE";
const UNASSIGN_ATTENDEE = "UNASSIGN_ATTENDEE";
const CHANGE_EVENT_DETAILS = "CHANGE_EVENT_DETAILS";
const CREATE_BOAT = "CREATE_BOAT";

export { ASSIGN_ATTENDEE, UNASSIGN_ATTENDEE, CHANGE_EVENT_DETAILS, CREATE_BOAT }