export const SAVE_EVENT_DETAILS_ERROR = "SAVE_EVENT_DETAILS_ERROR"
export const SAVE_EVENT_DETAILS_REQUEST = "SAVE_EVENT_DETAILS_REQUEST"
export const SAVE_EVENT_DETAILS_SUCCESS = "SAVE_EVENT_DETAILS_SUCCESS"
export const SET_INITIAL_STATE "SET_INITIAL_STATE"
