--CREATE VIEW [WaterEvents].[AttendeeNames] 
--AS 
--SELECT [AttendeeId], [GivenName], [Surname]
--FROM [WaterEvents].[AnonymousAttendees]
--UNION ALL
--SELECT [AttendeeId], [GivenName], [Surname]
--FROM [WaterEvents].[RegisteredAttendeeNames]